services:
  api:
    build: .
    restart: unless-stopped
    environment:
      - RACK_ENV=production
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conectors.rule=Host(`archcode.space`)"
      - "traefik.http.routers.conectors.entrypoints=websecure"
      - "traefik.http.routers.conectors.tls.certresolver=letsencrypt"
      - "traefik.http.services.conectors.loadbalancer.server.port=9292"

networks:
  traefik-public:
    external: true
